### PR TITLE
Add pitch to player state

### PR DESCRIPTION
**Pull request by IceTank**

### CODE REVIEW

**Review by andriycraft — APPROVED** [review]

**Comment by rom1504** [comment]
how come it worked before / what will change after this PR ?

**Comment by IceTank** [comment]
> how come it worked before / what will change after this PR ?

There was never anything that actually used pitch. Only yaw was used in physics calculations.

**Comment by rom1504** [comment]
is something using pitch now ?

**Comment by IceTank** [comment]
> is something using pitch now ?

No. But if anything ever want to implement something like flying with an elytra it might be used. I can also be used when you are trying to simulate the bot's movements without moving the bot. Pathfinder does simulation but does not use pitch as it always sets pitch to 0 for simplicity.

**Comment by IceTank** [comment]
@rom1504 is there anything that prevents this from being merged?

**Comment by rom1504** [comment]
We can merge but is this only adding an unused line of code or is there any plan to use it ?

**Comment by rom1504** [comment]
Please add to doc (in readme)

**Pull request merged**
