### PR TITLE
Use prismarine-nbt to cleanly handle nbt + fix post-flattening enchants

### PR DESCRIPTION
**Pull request by IdanHo**
This change uses prismarine-nbt to simplify the object down to a common format. I've also found that on mc 1.14+ the "id" property of the enchant is now a string in the format of "minecraft:enchant_name", so ive added support for that as well.
Unfortunately this is still crashing, as it seems like no enchantments data was specified post 1.13.2 in minecraft-data, so enchantmentsByName is null on those versions. This can be fixed for versions 1.14-1.15.2 just by adding the datapath to the 1.13.2 enchantments data (as no enchantments were added in those versions), and can be fixed for 1.16+ by PrismarineJS/minecraft-data#325, as new enchantments were added in that version.
Once minecraft-data is fixed and this is merged, this should fix PrismarineJS/mineflayer#1270

### CODE REVIEW

**Comment by embeddedt** [comment]
This is crashing when connecting to Spigot 1.8.9. The crash occurs because `nbt.simplify(boots.nbt).Enchantments` is undefined. Reverting to the previous code appears to fix the issue.

**Comment by rom1504** [comment]
@embeddedt can you fix it by adding some if there (and PR) ?

**Comment by embeddedt** [comment]
@rom1504 I've opened #26 to address this.

**Comment by rom1504** [comment]
@embeddedt thanks, merged and released

**Pull request merged**
