### PR TITLE
fix attribute key 'uuid' vs 'UUID'

### PR DESCRIPTION
**Pull request by WhoTho**

### CODE REVIEW

**Review by WhoTho — COMMENTED** [review]
When setting attribute modifiers from the server, the keyword 'uuid' is capitalized.

This fix just checks if the uuid keyword is capitalized or not.
As far as I am aware we could just change line 397 in the prismarine-physics/index.js from 'uuid' to 'UUID', but I do not know if there are other sections of code that use the key 'uuid'.

Check wiki to see that UUID is caps. https://wiki.vg/Protocol#Update_Attributes

**Comment by rob9315** [comment]
no, modifiers are a binary datastructure. their capitalization or naming in general does not matter.

**Comment by rob9315** [comment]
if the code is checking the wrong capitalization, that is a bug and should be fixed. you can look up the actual names used in [minecraft-data](https://github.com/prismarineJS/minecraft-data/), specifically the protocol.json files. they determine the naming used.

**Comment by rob9315** [comment]
`uuid` is [supposed to be lowercase](https://github.com/PrismarineJS/minecraft-data/blob/acd6197d6bf8adb429390e043a7ecfb01c4bb051/data/pc/1.19/protocol.json#L4287), changing it would be a breaking api change.

**Comment by WhoTho** [comment]
well im fine with it being lowercase, but it doesnt match up with the keys sent by the server and thus fails the ```modifer.uuid === uuid``` check.

**Comment by rob9315** [comment]
there is no capitalized uuid field anywhere in the protocol except for [this one](https://github.com/PrismarineJS/minecraft-data/blob/acd6197d6bf8adb429390e043a7ecfb01c4bb051/data/pc/1.19/protocol.json#L3266) which has nothing to do with modifiers

**Comment by rob9315** [comment]
the capitalized uuid has to be set somewhere else

**Comment by WhoTho** [comment]
the capitalized uuid comes directly from the server (shown by the last picture which uses pakkit to show packets). either way the fix im proposing should cover both so it doesnt matter.

**Comment by rob9315** [comment]
which version is this?

**Comment by rob9315** [comment]
it seems the naming was changed at some point, 1.7 has `UUID` when 1.19 has `uuid`

**Comment by rob9315** [comment]
1.7 and 1.8 have `UUID` when all other versions have `uuid`, i'll make a pr to adjust 1.7 and 1.8.

**Comment by rob9315** [comment]
after that is merged, this issue should be fixed.

**Comment by rom1504** [comment]
fixed in mcdata

**Pull request closed without merging**
